const fs=require('fs');const path=require('path');const crypto=require('crypto')
const MAX_BYTES=8*1024*1024,MAX_BLOCKS=250000
function safeName(value){return String(value||'schematic').replace(/\.schem$/i,'').replace(/[^a-z0-9 _.-]/gi,'_').trim().slice(0,80)||'schematic'}
function varints(buffer,count){const out=[];let value=0,shift=0;for(const byte of buffer){value|=(byte&127)<<shift;if(byte&128){shift+=7;if(shift>28)throw new Error('Invalid schematic BlockData.')}else{out.push(value);value=0;shift=0;if(out.length===count)break}}if(out.length<count)throw new Error('Schematic BlockData is incomplete.');return out}
function blockName(state){return String(state||'minecraft:air').split('[')[0].replace(/^minecraft:/,'')}
function decode(document){const root=document.Schematic||document,blockSection=root.Blocks||root;const width=Number(root.Width),height=Number(root.Height),length=Number(root.Length),count=width*height*length;if(![width,height,length,count].every(Number.isInteger)||width<1||height<1||length<1||count>MAX_BLOCKS)throw new Error('Invalid or too large schematic dimensions.');const palette=blockSection.Palette||root.Palette||{},reverse=Object.fromEntries(Object.entries(palette).map(([name,id])=>[Number(id),blockName(name)])),raw=blockSection.Data||root.BlockData;if(!raw)throw new Error('This .schem has no block data.');const data=Buffer.isBuffer(raw)?raw:Buffer.from(raw);const indices=varints(data,count),blocks=[];for(let index=0;index<count;index++){const name=reverse[indices[index]]||'air';if(name==='air'||name==='cave_air'||name==='void_air')continue;const x=index%width,z=Math.floor(index/width)%length,y=Math.floor(index/(width*length));blocks.push({x,y,z,name})}return{width,height,length,blockCount:blocks.length,materials:blocks.reduce((all,b)=>(all[b.name]=(all[b.name]||0)+1,all),{}),blocks}}
class SchematicStore{
 constructor(root,nbt){this.root=root;this.nbt=nbt;fs.mkdirSync(root,{recursive:true})}
 list(){return fs.readdirSync(this.root,{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>this.get(x.name,false)).filter(Boolean).sort((a,b)=>b.createdAt-a.createdAt)}
 get(id,includeBlocks=true){if(!/^[a-f0-9-]{36}$/.test(String(id)))return null;try{const meta=JSON.parse(fs.readFileSync(path.join(this.root,id,'meta.json'),'utf8'));if(includeBlocks)meta.blocks=JSON.parse(fs.readFileSync(path.join(this.root,id,'blocks.json'),'utf8'));return meta}catch{return null}}
 async save(filename,buffer){if(!Buffer.isBuffer(buffer)||!buffer.length||buffer.length>MAX_BYTES)throw new Error('Choose a .schem file smaller than 8 MB.');if(!/\.schem$/i.test(filename))throw new Error('Only .schem files are allowed.');const parsed=await new Promise((resolve,reject)=>this.nbt.parse(buffer,(error,data)=>error?reject(error):resolve(this.nbt.simplify(data))));const decoded=decode(parsed),id=crypto.randomUUID(),folder=path.join(this.root,id),createdAt=Date.now(),meta={schemaVersion:1,id,name:safeName(filename),filename:safeName(filename)+'.schem',createdAt,...decoded};delete meta.blocks;fs.mkdirSync(folder,{recursive:true});fs.writeFileSync(path.join(folder,'source.schem'),buffer);fs.writeFileSync(path.join(folder,'blocks.json'),JSON.stringify(decoded.blocks));fs.writeFileSync(path.join(folder,'meta.json'),JSON.stringify(meta,null,2));return meta}
 remove(id){const item=this.get(id,false);if(!item)return false;fs.rmSync(path.join(this.root,id),{recursive:true,force:true});return true}
}
function transformBlocks(blocks,rotation,width,length){return blocks.map(block=>{if(rotation===90)return{x:length-1-block.z,y:block.y,z:block.x,name:block.name};if(rotation===180)return{x:width-1-block.x,y:block.y,z:length-1-block.z,name:block.name};if(rotation===270)return{x:block.z,y:block.y,z:width-1-block.x,name:block.name};return{...block}})}
module.exports={SchematicStore,decode,varints,transformBlocks,MAX_BYTES}
