'use strict'
const fs=require('fs');const path=require('path')
const readJson=(file,fallback={})=>{try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return fallback}}
const finite=value=>Number.isFinite(Number(value))?Number(value):null
function paginate(items,query={}){const page=Math.max(1,Number(query.page)||1),limit=Math.max(1,Math.min(200,Number(query.limit)||50));return{items:items.slice((page-1)*limit,page*limit),page,limit,total:items.length}}
class DashboardService{
 constructor(options){Object.assign(this,options);this.skillCache={at:0,value:[]}}
 botDto(config){const live=this.team.registry.get(config.id);const telemetry=this.telemetry(config.id);const status=telemetry?.data||{};const heartbeat=live?.lastHeartbeatAt||Date.parse(telemetry?.receivedAt||'')||null;return{botId:config.id,instanceId:live?.instanceId||status.team?.instanceId||null,displayName:config.name,status:!live?.online?'offline':live.safetyState==='unsafe'?'unsafe':live.currentTaskId?'working':status.mode||'idle',online:Boolean(live?.online||status.connected),server:{host:config.host,port:config.port,version:config.version},worldId:live?.worldId||status.team?.worldId||null,dimension:live?.position?.dimension||status.dimension||null,position:live?.position||normalizePosition(status.position),health:finite(live?.health??status.health),food:finite(live?.food??status.food),armor:status.equipment||null,inventorySummary:live?.inventorySummary||status.inventorySummary||summarizeInventory(status.inventory),currentTask:live?.currentTaskId||status.reliableTask?.currentTask||status.currentTask||null,currentGoal:live?.currentTeamGoalId||null,activeSkill:live?.currentSkill||status.activeSkill||null,currentStep:status.currentStep||status.reliableTask?.currentStep||null,progress:this.taskProgress(live?.currentTaskId),retry:{attempt:status.attempt||status.reliableTask?.attempt||0,max:status.maxAttempts||status.reliableTask?.maxAttempts||0},pathfinder:status.pathStatus||null,safetyState:live?.safetyState||status.safetyState||'unknown',lastError:live?.lastError||status.lastError||null,lastHeartbeatAt:heartbeat,heartbeatAgeMs:heartbeat?Date.now()-heartbeat:null,uptimeMs:live?.registeredAt?Date.now()-live.registeredAt:null,capabilities:live?.capabilities||[],skillVersions:live?.skillVersions||{},recentActivities:(status.taskLog||[]).slice(0,20),debug:this.settings().debugMode?{planner:status.planner,currentPlan:status.currentPlan,reliableTask:status.reliableTask,socketConnected:Boolean(telemetry?.socket?.connected)}:undefined}}
 bots(){return this.configBots().map(bot=>this.botDto(bot))}
 bot(id){return this.bots().find(bot=>bot.botId===id)||null}
 taskProgress(id){const task=this.team.findTask(id);return task?.progress||null}
 taskDto(task){const dependencies=(task.dependencies||[]).map(id=>this.team.findTask(id)).filter(Boolean);return{...task,progress:task.progress||null,dependencyStatus:dependencies.map(item=>({id:item.id,status:item.status})),durationMs:task.startedAt?(task.completedAt||task.failedAt||Date.now())-task.startedAt:null,reservations:this.team.store.state.reservations.filter(item=>item.taskId===task.id)}}
 tasks(query={}){let values=this.team.tasks().filter(t=>(!query.botId||t.assignedBotId===query.botId)&&(!query.goalId||t.teamGoalId===query.goalId)&&(!query.status||t.status===query.status)&&(!query.skill||t.skill===query.skill)&&(!query.worldId||t.worldId===query.worldId)&&(!query.errorCode||t.lastError===query.errorCode)&&(!query.priority||Number(t.priority)===Number(query.priority))).map(t=>this.taskDto(t));return paginate(values,query)}
 goalDto(goal){const tasks=goal.taskIds.map(id=>this.team.findTask(id)).filter(Boolean),completed=tasks.filter(t=>t.status==='completed').length;const required=goal.requirements||{},containers=Object.values(this.team.inventory.snapshot().containers||{}).filter(c=>c.worldId===goal.worldId);const collected=Object.fromEntries(Object.keys(required).map(item=>[item,containers.reduce((total,c)=>total+Number(c.contents?.[item]||0),0)]));const starts=tasks.map(t=>t.startedAt).filter(Boolean),finishes=tasks.map(t=>t.completedAt).filter(Boolean);return{...goal,title:goal.title||goal.type.replaceAll('_',' '),progress:tasks.length?completed/tasks.length:0,collected,taskCounts:Object.fromEntries([...new Set(tasks.map(t=>t.status))].map(status=>[status,tasks.filter(t=>t.status===status).length])),assignedBots:[...new Set(tasks.map(t=>t.assignedBotId).filter(Boolean))],blockers:tasks.filter(t=>['blocked','failed'].includes(t.status)).map(t=>({taskId:t.id,errorCode:t.lastError})),estimatedRemainingSteps:tasks.length-completed,startedAt:starts.length?Math.min(...starts):null,completedAt:goal.status==='completed'?(finishes.length?Math.max(...finishes):goal.updatedAt):null}}
 goals(){return this.team.goals().map(goal=>this.goalDto(goal))}
 skills(){if(Date.now()-this.skillCache.at<15000)return this.skillCache.value;const bots=this.team.registry.list().map(bot=>({...bot}));for(const config of this.configBots()){if(bots.some(bot=>bot.botId===config.id))continue;const learned=readJson(path.join(this.resolveBotFolder(config),'knowledge','learned.json'),{});bots.push({botId:config.id,skillStats:learned.skillStats||{},skillVersions:{},skills:[]})}const names=[...new Set(bots.flatMap(bot=>Object.keys(bot.skillStats||{})).concat(bots.flatMap(bot=>Object.keys(bot.skillVersions||{}))).concat(bots.flatMap(bot=>(bot.skills||[]).map(skill=>skill.name))))];const value=names.map(name=>{const entries=bots.map(bot=>({botId:bot.botId,stats:bot.skillStats?.[name]})).filter(e=>e.stats);const executions=entries.reduce((n,e)=>n+Number(e.stats.executions||0),0),successes=entries.reduce((n,e)=>n+Number(e.stats.successes||0),0),failures=entries.reduce((n,e)=>n+Number(e.stats.failures||0),0);const best=[...entries].sort((a,b)=>Number(b.stats.successRate||0)-Number(a.stats.successRate||0))[0],metadata=bots.flatMap(bot=>bot.skills||[]).find(skill=>skill.name===name);return{name,description:metadata?.description||null,version:metadata?.version||bots.find(b=>b.skillVersions?.[name])?.skillVersions[name]||null,capabilities:bots.filter(bot=>(bot.capabilities||[]).includes(name)).map(bot=>bot.botId),executions,successes,failures,successRate:executions?successes/executions:null,averageDurationMs:executions?entries.reduce((n,e)=>n+Number(e.stats.totalDurationMs||0),0)/executions:null,recentTrend:trend(entries.flatMap(e=>e.stats.recent||[])),commonErrors:common(entries.flatMap(e=>e.stats.lastErrorCodes||[])),bestBotId:best?.botId||null,lastUsedAt:entries.map(e=>e.stats.lastUsed).filter(Boolean).sort().at(-1)||null,byBot:entries}});this.skillCache={at:Date.now(),value};return value}
 experiences(query={}){const values=[];for(const bot of this.configBots()){const learned=readJson(path.join(this.resolveBotFolder(bot),'knowledge','learned.json'),{});for(const exp of learned.experiences||[])if((!query.botId||exp.botId===query.botId)&&(!query.worldId||exp.worldId===query.worldId))values.push({...exp,sourceBotId:bot.id})}return paginate(values.sort((a,b)=>Date.parse(b.createdAt||0)-Date.parse(a.createdAt||0)),query)}
 logistics(){const ledger=this.team.inventory.snapshot(),reservations=Object.values(ledger.reservations||{});return{containers:Object.values(ledger.containers||{}).map(c=>({...c,items:Object.entries(c.contents||{}).map(([item,present])=>{const reserved=reservations.filter(r=>r.containerId===c.id&&r.item===item).reduce((n,r)=>n+r.amount,0);return{item,present,reserved,available:Math.max(0,present-reserved)}})})),reservations,botInventories:this.bots().map(b=>({botId:b.displayName,internalBotId:b.botId,displayName:b.displayName,worldId:b.worldId,server:b.server,inventorySummary:b.inventorySummary}))}}
 overview(){const bots=this.bots(),tasks=this.team.tasks(),goals=this.goals(),skills=this.skills(),logistics=this.logistics();return{generatedAt:Date.now(),worlds:[...new Set(bots.map(b=>b.worldId).filter(Boolean))],counts:{onlineBots:bots.filter(b=>b.online).length,offlineBots:bots.filter(b=>!b.online).length,idleBots:bots.filter(b=>b.status==='idle').length,activeTasks:tasks.filter(t=>['reserved','assigned','running'].includes(t.status)).length,blockedTasks:tasks.filter(t=>t.status==='blocked').length,activeGoals:goals.filter(g=>['ready','running','blocked'].includes(g.status)).length,knownSkills:skills.length},averageSkillSuccessRate:average(skills.map(s=>s.successRate).filter(v=>v!==null)),recentErrors:this.events.query({level:'error',limit:10}).items,warnings:this.warnings(bots,tasks,logistics),bots,goals:goals.filter(g=>g.status!=='completed').slice(0,10),teamInventory:logistics.containers}}
 warnings(bots,tasks,logistics){const warnings=[];const unsafeBots=bots.filter(bot=>bot.online&&bot.safetyState==='unsafe');if(unsafeBots.length)warnings.push('Unsafe bot'+(unsafeBots.length===1?'':'s')+': '+unsafeBots.map(bot=>bot.displayName).join(', ')+'.');if(tasks.some(t=>t.status==='blocked'))warnings.push('Team tasks are blocked.');if(logistics.containers.some(c=>Date.now()-Number(c.lastVerifiedAt||0)>300000))warnings.push('Container inventory is stale.');return warnings}
}
function normalizePosition(p){return p?{x:finite(p.x),y:finite(p.y),z:finite(p.z),dimension:p.dimension||null}:null}function summarizeInventory(items=[]){const out={};for(const item of items||[])if(item?.name)out[item.name]=(out[item.name]||0)+Number(item.count||0);return out}function average(values){return values.length?values.reduce((a,b)=>a+b,0)/values.length:null}function common(values){const counts={};for(const value of values)counts[value]=(counts[value]||0)+1;return Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([errorCode,count])=>({errorCode,count}))}function trend(values){if(values.length<4)return'insufficient';const half=Math.floor(values.length/2),old=average(values.slice(0,half).map(Number)),recent=average(values.slice(half).map(Number));return recent>old+.1?'improving':recent<old-.1?'declining':'stable'}
module.exports={DashboardService,paginate,summarizeInventory,trend}
