const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const os=require('os');const path=require('path');const {EventEmitter}=require('events')
const {BotRegistry}=require('../src/team/botRegistry');const {scoreBotForTask,dependenciesMet}=require('../src/team/assignmentEngine');const {ReservationStore}=require('../src/team/reservationStore');const {InventoryLedger}=require('../src/team/inventoryLedger');const {TeamStore}=require('../src/team/teamStore');const {TeamCoordinator}=require('../src/team/teamCoordinator')
function registration(id='a',instance='i1',worldId='w'){return{botId:id,instanceId:instance,worldId,capabilities:['collectWood','mineStone','craftBasicItems','mineIron','smeltItems','storeItems'],skillStats:{collectWood:{successRate:.9}},position:{x:0,y:64,z:0},health:20,food:20,safetyState:'safe'}}
function temporaryStore(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'team-store-'));return{root,store:new TeamStore(path.join(root,'team.json'))}}
class Channel extends EventEmitter{emit(name,value){super.emit(name,value);return true}}

test('registry replaces duplicate runtime instances and rejects stale heartbeats',()=>{let now=1;const r=new BotRegistry({now:()=>now,offlineAfterMs:10});r.register(registration());const replacement=r.register(registration('a','i2'));assert.equal(replacement.replaced,true);assert.throws(()=>r.heartbeat({botId:'a',instanceId:'i1'}),/STALE/);r.heartbeat({botId:'a',instanceId:'i2',health:18});assert.equal(r.get('a').health,18)})
test('heartbeat timeout marks a bot offline',()=>{let now=0;const r=new BotRegistry({now:()=>now,offlineAfterMs:10});r.register(registration());now=11;assert.equal(r.sweep()[0].online,false)})
test('assignment rejects wrong world and capabilities and rewards skill success',()=>{const task={worldId:'w',requiredCapabilities:['collectWood'],skill:'collectWood',destination:{x:10,y:64,z:0}};assert.equal(scoreBotForTask({...registration(),worldId:'other',online:true},task),-Infinity);assert.equal(scoreBotForTask({...registration(),capabilities:[],online:true},task),-Infinity);assert.ok(scoreBotForTask({...registration(),online:true},task)>100)})
test('dependencies require completed predecessor tasks',()=>{const task={dependencies:['one']};assert.equal(dependenciesMet(task,[{id:'one',status:'running'}]),false);assert.equal(dependenciesMet(task,[{id:'one',status:'completed'}]),true)})
test('area and object reservations are exclusive and expire',()=>{let now=0;const state={reservations:[]};const r=new ReservationStore(state,{now:()=>now});r.create({id:'a',type:'area',worldId:'w',ownerBotId:'a',ownerInstanceId:'1',bounds:{min:{x:0,y:0,z:0},max:{x:5,y:5,z:5}},expiresAt:10});assert.throws(()=>r.create({type:'area',worldId:'w',ownerBotId:'b',ownerInstanceId:'2',bounds:{min:{x:4,y:0,z:0},max:{x:8,y:5,z:5}},expiresAt:10}),/CONFLICT/);r.create({id:'chest',type:'object',objectId:'w:chest:1:2:3',worldId:'w',ownerBotId:'a',ownerInstanceId:'1',expiresAt:10});assert.throws(()=>r.create({type:'object',objectId:'w:chest:1:2:3',worldId:'w',ownerBotId:'b',ownerInstanceId:'2',expiresAt:10}),/CONFLICT/);now=11;assert.equal(r.expire().length,2)})
test('disconnect cleanup removes all owner reservations',()=>{const state={reservations:[]};const r=new ReservationStore(state);r.create({type:'task',taskId:'t',worldId:'w',ownerBotId:'a',ownerInstanceId:'i',expiresAt:Date.now()+1000});assert.equal(r.releaseOwner('a','i').length,1)})
test('inventory cannot be reserved twice beyond verified stock',()=>{let now=0;const state={inventory:{containers:{},reservations:{}}};const ledger=new InventoryLedger(state,{now:()=>now});ledger.updateContainer({id:'c',worldId:'w',contents:{iron_ingot:16}});ledger.reserve({id:'one',containerId:'c',worldId:'w',item:'iron_ingot',amount:12,botId:'a',expiresAt:20});assert.equal(ledger.available('c','iron_ingot'),4);assert.throws(()=>ledger.reserve({containerId:'c',worldId:'w',item:'iron_ingot',amount:5,botId:'b',expiresAt:20}),/ITEMS_UNAVAILABLE/);now=21;assert.equal(ledger.available('c','iron_ingot'),16)})
test('task claim has one owner and follows accepted-running-completed transitions',()=>{const {root,store}=temporaryStore();const coordinator=new TeamCoordinator(store,{taskAcceptTimeoutMs:1000});try{const channel=new Channel();coordinator.register(registration(),channel);const goal=coordinator.createGoal({type:'obtain_iron_ingots',amount:2,worldId:'w'});const offered=coordinator.tasks().find(t=>t.status==='reserved');assert.ok(offered);assert.throws(()=>coordinator.accept({taskId:offered.id,botId:'other',instanceId:'i1'}),/REJECTED/);coordinator.accept({taskId:offered.id,botId:'a',instanceId:'i1'});coordinator.start({taskId:offered.id,botId:'a',instanceId:'i1'});coordinator.complete({taskId:offered.id,botId:'a',instanceId:'i1',result:{success:true}});assert.equal(offered.status,'completed');assert.equal(goal.status==='ready'||goal.status==='running',true)}finally{coordinator.close();fs.rmSync(root,{recursive:true,force:true})}})
test('offline bot returns active task for reassignment',()=>{const {root,store}=temporaryStore();const c=new TeamCoordinator(store,{taskAcceptTimeoutMs:1000});try{const channel=new Channel();c.register(registration(),channel);c.createGoal({worldId:'w',amount:2});const task=c.tasks().find(t=>t.status==='reserved');c.accept({taskId:task.id,botId:'a',instanceId:'i1'});c.start({taskId:task.id,botId:'a',instanceId:'i1'});c.unregister('a','i1');assert.equal(task.status,'available');assert.equal(task.assignedBotId,null)}finally{c.close();fs.rmSync(root,{recursive:true,force:true})}})
test('Hub restart preserves completed work and requeues running work',()=>{const {root,store}=temporaryStore();try{store.state.tasks=[{id:'done',status:'completed'},{id:'work',status:'running',assignedBotId:'a',assignedInstanceId:'i'}];store.save();const loaded=new TeamStore(store.file);assert.equal(loaded.state.tasks[0].status,'completed');assert.equal(loaded.state.tasks[1].status,'available');assert.equal(loaded.state.reservations.length,0)}finally{fs.rmSync(root,{recursive:true,force:true})}})
test('task acceptance timeout makes an offer available again',async()=>{const {root,store}=temporaryStore();const c=new TeamCoordinator(store,{taskAcceptTimeoutMs:15});try{c.register(registration(),new Channel());c.createGoal({worldId:'w',amount:2});const task=c.tasks().find(t=>t.status==='reserved');await new Promise(resolve=>setTimeout(resolve,30));assert.equal(task.status,'available');assert.equal(task.lastError,'TASK_TIMEOUT')}finally{c.close();fs.rmSync(root,{recursive:true,force:true})}})
test('single-bot iron teamwork template completes dependencies in order',()=>{const {root,store}=temporaryStore();const c=new TeamCoordinator(store,{taskAcceptTimeoutMs:1000});try{c.register(registration(),new Channel());const goal=c.createGoal({worldId:'w',amount:4,target:{position:{x:1,y:64,z:1}}});for(let guard=0;guard<10&&goal.status!=='completed';guard++){const task=c.tasks().find(item=>item.teamGoalId===goal.id&&item.status==='reserved');assert.ok(task,'next dependency should be offered');c.accept({taskId:task.id,botId:'a',instanceId:'i1'});c.start({taskId:task.id,botId:'a',instanceId:'i1'});c.complete({taskId:task.id,botId:'a',instanceId:'i1',result:{success:true}})}assert.equal(goal.status,'completed');assert.ok(c.tasks().filter(task=>task.teamGoalId===goal.id).every(task=>task.status==='completed'))}finally{c.close();fs.rmSync(root,{recursive:true,force:true})}})
