'use strict'
const { randomUUID }=require('crypto')
class TeamPlanner{
 createGoal(request,onlineBots=[]){const now=Date.now();const id=request.id||`goal-${randomUUID()}`;const type=request.type||'obtain_iron_ingots';const amount=Math.max(1,Math.min(2304,Number(request.amount||request.requirements?.iron_ingot||16)));if(type!=='obtain_iron_ingots')throw new Error('UNSUPPORTED_TEAM_GOAL');const worldId=String(request.worldId||'');if(!worldId)throw new Error('WORLD_MISMATCH');const goal={id,type,status:'ready',priority:Number(request.priority||50),worldId,requestedBy:String(request.requestedBy||'api'),target:request.target||{},requirements:{iron_ingot:amount},taskIds:[],createdAt:now,updatedAt:now};const count=Math.max(1,onlineBots.filter(bot=>bot.online&&bot.worldId===worldId).length);const specs=count===1?
 [{key:'iron-chain',skill:'mineResource',cap:'mineIron',target:{item:'raw_iron',amount}},{key:'smelt',skill:'smeltItem',cap:'smeltItems',target:{item:'iron_ingot',inputItem:'raw_iron',amount},deps:['iron-chain']},{key:'deposit',skill:'storeItems',cap:'storeItems',target:{item:'iron_ingot',amount},deps:['smelt']}]:
 [{key:'wood',skill:'collectWood',cap:'collectWood',target:{item:'oak_log',amount:Math.max(8,Math.ceil(amount/2))}},{key:'stone',skill:'collectStone',cap:'mineStone',target:{item:'cobblestone',amount:8}},{key:'pickaxe',skill:'craftTool',cap:'craftBasicItems',target:{item:'stone_pickaxe',amount:1},deps:['stone']},{key:'iron',skill:'mineResource',cap:'mineIron',target:{item:'raw_iron',amount},deps:['pickaxe']},{key:'fuel',skill:'collectWood',cap:'collectWood',target:{item:'oak_log',amount:Math.max(2,Math.ceil(amount/8))},deps:['wood']},{key:'smelt',skill:'smeltItem',cap:'smeltItems',target:{item:'iron_ingot',inputItem:'raw_iron',amount},deps:['iron','fuel']},{key:'deposit',skill:'storeItems',cap:'storeItems',target:{item:'iron_ingot',amount},deps:['smelt']}]
 const ids=Object.fromEntries(specs.map(spec=>[spec.key,`task-${randomUUID()}`]));const tasks=specs.map(spec=>({id:ids[spec.key],teamGoalId:id,worldId,type:'skill',skill:spec.skill,target:spec.target,destination:spec.key==='deposit'?(request.target?.position||null):null,status:'available',priority:goal.priority,assignedBotId:null,assignedInstanceId:null,requiredCapabilities:[spec.cap],dependencies:(spec.deps||[]).map(key=>ids[key]),reservedResources:[],retryCount:0,maxRetries:3,reservationExpiresAt:null,createdAt:now,updatedAt:now}));goal.taskIds=tasks.map(task=>task.id);return{goal,tasks}}
}
module.exports={TeamPlanner}
