'use strict'
const { EventEmitter }=require('events');const { BotRegistry }=require('./botRegistry');const { AssignmentEngine,dependenciesMet }=require('./assignmentEngine');const { ReservationStore }=require('./reservationStore');const { InventoryLedger }=require('./inventoryLedger');const { TeamPlanner }=require('./teamPlanner')
const ERRORS=new Set(['BOT_OFFLINE','TASK_REJECTED','TASK_TIMEOUT','TASK_CANCELLED','CAPABILITY_MISSING','DEPENDENCY_FAILED','RESERVATION_CONFLICT','RESERVATION_EXPIRED','AREA_BLOCKED','CONTAINER_BUSY','INVENTORY_CHANGED','ITEMS_UNAVAILABLE','WORLD_MISMATCH','PATH_FAILED','PATH_STUCK','UNSAFE_ENVIRONMENT','VALIDATION_FAILED'])
class TeamCoordinator extends EventEmitter{
 constructor(store,options={}){super();this.store=store;this.options={enabled:true,botOfflineAfterMs:12000,taskAcceptTimeoutMs:10000,taskReservationMs:30000,maxTaskRetries:3,...options};this.now=options.now||Date.now;this.registry=new BotRegistry({offlineAfterMs:this.options.botOfflineAfterMs,now:this.now});this.assignment=new AssignmentEngine();this.reservations=new ReservationStore(store.state,{now:this.now});this.inventory=new InventoryLedger(store.state,{now:this.now});this.planner=new TeamPlanner();this.acceptTimers=new Map()}
 register(payload,channel){if(!this.options.enabled)return null;const result=this.registry.register(payload,channel);if(result.replaced)this.handleOffline(result.previous,'BOT_OFFLINE');this.emit('changed');this.assign();return result.bot}
 heartbeat(payload){const bot=this.registry.heartbeat(payload);const peers=this.registry.list().filter(peer=>peer.online&&peer.worldId===bot.worldId&&peer.botId!==bot.botId);bot.channel?.emit?.('team:peers',{peers});this.emit('changed');return bot}
 unregister(botId,instanceId){const bot=this.registry.get(botId);if(!this.registry.unregister(botId,instanceId))return false;this.handleOffline(bot,'BOT_OFFLINE');return true}
 createGoal(request){if(!this.options.enabled)throw new Error('TEAM_DISABLED');const logistics=(this.options.logisticsContainers||[]).find(item=>item.enabled!==false&&item.worldId===request.worldId);const normalized={...request,target:request.target?.position?request.target:(logistics?{...request.target,position:logistics.position,containerId:logistics.id}:request.target)};const planned=this.planner.createGoal(normalized,this.registry.list());this.store.state.goals.push(planned.goal);this.store.state.tasks.push(...planned.tasks);this.store.save();this.emit('event',{type:'goal.created',goalId:planned.goal.id,level:'info',message:`Team goal ${planned.goal.type} created`});this.emit('changed');this.assign();return planned.goal}
 tasks(){return this.store.state.tasks}
 goals(){return this.store.state.goals}
 findTask(id){return this.tasks().find(task=>task.id===id)||null}
 transition(task,status,patch={}){const allowed={available:['reserved','cancelled'],reserved:['assigned','available','cancelled'],assigned:['running','available','blocked','cancelled'],running:['completed','failed','blocked','cancelled'],blocked:['available','failed','cancelled'],failed:['available'],completed:[],cancelled:[]};if(!allowed[task.status]?.includes(status))throw new Error(`INVALID_TASK_TRANSITION:${task.status}:${status}`);Object.assign(task,patch,{status,updatedAt:this.now()});this.updateGoal(task.teamGoalId);this.store.save();this.emit('changed');return task}
 assign(){if(!this.options.enabled)return;for(const task of this.tasks().filter(x=>x.status==='available')){const choice=this.assignment.choose(task,this.registry.list(),this.tasks());if(!choice)continue;this.offer(task,choice.bot)}}
 offer(task,bot){bot.currentTaskId=task.id;bot.currentTeamGoalId=task.teamGoalId;this.transition(task,'reserved',{assignedBotId:bot.botId,assignedInstanceId:bot.instanceId,reservationExpiresAt:this.now()+this.options.taskAcceptTimeoutMs,assignmentScore:choiceSafeScore(this.assignment,bot,task)});this.emit('event',{type:'task.assigned',botId:bot.botId,taskId:task.id,goalId:task.teamGoalId,level:'info',message:`Hub offered ${task.skill} to ${bot.botId}`});bot.channel?.emit?.('team:task-offer',{task,acceptBy:task.reservationExpiresAt});const timer=setTimeout(()=>{this.acceptTimers.delete(task.id);if(task.status==='reserved'){this.releaseBotTask(bot.botId,task.id);this.transition(task,'available',{assignedBotId:null,assignedInstanceId:null,reservationExpiresAt:null,lastError:'TASK_TIMEOUT',excludedInstanceIds:[...(task.excludedInstanceIds||[]),bot.instanceId]});this.emit('event',{type:'task.timeout',botId:bot.botId,taskId:task.id,goalId:task.teamGoalId,level:'warning',errorCode:'TASK_TIMEOUT',message:`${bot.botId} did not accept ${task.skill}`})}this.assign()},this.options.taskAcceptTimeoutMs);timer.unref?.();this.acceptTimers.set(task.id,timer)}
 accept(payload){const task=this.findTask(payload.taskId);if(!task||task.status!=='reserved'||task.assignedBotId!==payload.botId||task.assignedInstanceId!==payload.instanceId)throw new Error('TASK_REJECTED');clearTimeout(this.acceptTimers.get(task.id));this.acceptTimers.delete(task.id);this.transition(task,'assigned',{reservationExpiresAt:this.now()+this.options.taskReservationMs});return task}
 reject(payload){const task=this.findTask(payload.taskId);if(!task||task.assignedInstanceId!==payload.instanceId)return false;clearTimeout(this.acceptTimers.get(task.id));this.acceptTimers.delete(task.id);this.releaseBotTask(payload.botId,task.id);this.transition(task,'available',{assignedBotId:null,assignedInstanceId:null,reservationExpiresAt:null,lastError:cleanError(payload.reason,'TASK_REJECTED'),excludedInstanceIds:[...(task.excludedInstanceIds||[]),payload.instanceId]});this.assign();return true}
 start(payload){const task=this.ownedTask(payload,'assigned');return this.transition(task,'running',{startedAt:this.now(),reservationExpiresAt:this.now()+this.options.taskReservationMs})}
 progress(payload){const task=this.ownedTask(payload);if(!['assigned','running','blocked'].includes(task.status))throw new Error('TASK_REJECTED');task.progress=payload.progress||{};task.reservationExpiresAt=this.now()+this.options.taskReservationMs;task.updatedAt=this.now();this.store.save();return task}
 block(payload){const task=this.ownedTask(payload);if(!['assigned','running'].includes(task.status))throw new Error('TASK_REJECTED');this.reservations.releaseOwner(payload.botId,payload.instanceId);this.releaseBotTask(payload.botId,task.id);this.transition(task,'blocked',{lastError:cleanError(payload.errorCode,'UNSAFE_ENVIRONMENT'),reservationExpiresAt:null});const timer=setTimeout(()=>{if(task.status==='blocked'){this.transition(task,'available',{assignedBotId:null,assignedInstanceId:null});this.assign()}},Math.min(10000,this.options.taskReservationMs));timer.unref?.();return task}
 complete(payload){const task=this.ownedTask(payload,'running');this.reservations.releaseOwner(payload.botId,payload.instanceId);this.releaseBotTask(payload.botId,task.id);const done=this.transition(task,'completed',{result:payload.result||{},completedAt:this.now(),reservationExpiresAt:null});this.assign();return done}
 fail(payload){const task=this.ownedTask(payload);const error=cleanError(payload.errorCode,'VALIDATION_FAILED');this.reservations.releaseOwner(payload.botId,payload.instanceId);this.releaseBotTask(payload.botId,task.id);task.retryCount=Number(task.retryCount||0)+1;if(task.retryCount<=Math.min(this.options.maxTaskRetries,task.maxRetries||3)){this.transition(task,'available',{assignedBotId:null,assignedInstanceId:null,reservationExpiresAt:null,lastError:error,excludedInstanceIds:[...(task.excludedInstanceIds||[]),payload.instanceId]})}else this.transition(task,'failed',{lastError:error,failedAt:this.now(),reservationExpiresAt:null});this.assign();return task}
 cancelTask(id){const task=this.findTask(id);if(!task)throw new Error('TASK_NOT_FOUND');const bot=this.registry.get(task.assignedBotId);bot?.channel?.emit?.('team:task-cancel',{taskId:id});if(['completed','cancelled'].includes(task.status))return task;return this.transition(task,'cancelled',{reservationExpiresAt:null})}
 ownedTask(payload,requiredStatus){const task=this.findTask(payload.taskId);if(!task||task.assignedBotId!==payload.botId||task.assignedInstanceId!==payload.instanceId||(requiredStatus&&task.status!==requiredStatus))throw new Error('TASK_REJECTED');return task}
 releaseBotTask(botId,taskId){const bot=this.registry.get(botId);if(bot?.currentTaskId===taskId){bot.currentTaskId=null;bot.currentTeamGoalId=null;bot.idleSince=this.now()}}
 handleOffline(bot,error='BOT_OFFLINE'){if(!bot)return;this.reservations.releaseOwner(bot.botId,bot.instanceId);this.inventory.releaseOwner(bot.botId,bot.instanceId);for(const task of this.tasks().filter(x=>x.assignedBotId===bot.botId&&x.assignedInstanceId===bot.instanceId&&!['completed','cancelled','failed'].includes(x.status))){clearTimeout(this.acceptTimers.get(task.id));this.acceptTimers.delete(task.id);Object.assign(task,{status:'available',assignedBotId:null,assignedInstanceId:null,reservationExpiresAt:null,lastError:error,updatedAt:this.now()})}this.store.save();this.emit('event',{type:'bot.offline',botId:bot.botId,level:'error',errorCode:error,message:`${bot.botId} went offline; tasks released`});this.emit('changed');this.assign()}
 sweep(){for(const bot of this.registry.sweep())this.handleOffline(bot);for(const task of this.tasks().filter(x=>['assigned','running'].includes(x.status)&&Number(x.reservationExpiresAt)<=this.now()))this.handleOffline(this.registry.get(task.assignedBotId),'TASK_TIMEOUT');this.reservations.expire();this.inventory.expire();this.store.save();this.assign()}
 updateGoal(id){const goal=this.goals().find(x=>x.id===id);if(!goal)return;const tasks=goal.taskIds.map(taskId=>this.findTask(taskId)).filter(Boolean);goal.status=tasks.every(x=>x.status==='completed')?'completed':tasks.some(x=>x.status==='running'||x.status==='assigned')?'running':tasks.some(x=>x.status==='failed')?'failed':tasks.some(x=>x.status==='blocked')?'blocked':'ready';goal.updatedAt=this.now()}
 snapshot(){return{enabled:this.options.enabled,bots:this.registry.list(),goals:this.goals(),tasks:this.tasks(),reservations:this.store.state.reservations,inventory:this.inventory.snapshot()}}
 close(){for(const timer of this.acceptTimers.values())clearTimeout(timer);this.acceptTimers.clear();this.store.save();this.removeAllListeners()}
}
function cleanError(value,fallback){const code=String(value||'').toUpperCase();return ERRORS.has(code)?code:fallback}
function choiceSafeScore(engine,bot,task){try{return require('./assignmentEngine').scoreBotForTask(bot,task)}catch{return 0}}
module.exports={TeamCoordinator,ERRORS}
